version: '2.1'
volumes:
  settings:
  dashboard-data:
  sensor-data:

services:
  data_services:
    build: ./data_services
    restart: always
    network_mode: host
    depends_on:
      - mqtt

  scheduler:
    restart: always
    build: ./scheduler
    privileged: true

  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'

  browser:
    image: balenablocks/browser:raspberrypi4-64
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host
    environment:
      - LAUNCH_URL=http://0.0.0.0:3000
      - ENABLE_GPU=1
      - KIOSK=1
      - LOCAL_HTTP_DELAY=7
      - PERSISTENT=1
    ports:
      - '5011' # management API (optional)
      - '35173' # Chromium debugging port (optional)
    volumes:
      - 'settings:/data' # Only required if using PERSISTENT flag (see below)

  influxdb:
    image: influxdb@sha256:73f876e0c3bd02900f829d4884f53fdfffd7098dd572406ba549eed955bf821f
    container_name: influxdb
    restart: always
    environment:
      - INFLUX_DATA_DIR=/data
    volumes:
      - 'sensor-data:/data'

  mqtt:
    image: arm32v6/eclipse-mosquitto@sha256:ec3e1dbb9e198ff04d62c2d0f6eff74cad7438c7d080b89a28428fb96c8479c4
    ports:
      - "1883:1883"
    restart: always

  connector:
    image: balenablocks/connector:raspberrypi4-64
    restart: always
    labels:
      io.balena.features.balena-api: '1' # necessary to discover services
    privileged: true # necessary to change container hostname
    depends_on:
      - mqtt
      - influxdb

  dashboard:
    image: balenablocks/dashboard:raspberrypi4-64
    restart: always
    volumes:
      - 'dashboard-data:/data'
    ports:
      - '3000:80'
